config/routes.rb
Rails.application.routes.draw do
  resources :articles

  root to: 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:destroy, :edit, :update]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save

    flash.notice = "#{@article.title} was created!"

    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy

    flash.notice = "#{@article.title} was deleted!"

    redirect_to articles_path
  end

  def edit

  end

  def update
    @article.update(article_params)

    flash.notice = "Article #{@article.title} Updated!"

    redirect_to articles_path(@article)
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
<ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
</ul>
<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :body %>
  <%= f.text_area :body %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article), class: 'article_title' %>
    </li>
  <% end %>
</ul>
<br>
<%= link_to "Create New Article", new_article_path, class: 'new_aritcle' %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= form_for(@article) do |f| %>
<ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
</ul>
<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :body %>
  <%= f.text_area :body %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<%= link_to 'Back to Articles', articles_path, class: 'articles_index'%>

<%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Really delete this article?"} %>

<%= link_to 'Edit', edit_article_path(@article)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="flash"><%= flash.notice %></p>
    <%= yield %>
  </body>
</html>